jetify-com/devbox-install-action

- action.yml
Fetch latest devbox release version.
I noticed that our installer script fails roughly half of the time getting the latest release version in cicd. This is to use a github action to get around that problem.
Why does it fail half of the time? I'm not sure yet...
> fetch latest devbox release version

- .github/workflows/test.yaml
- README.md
- action.yml
This PR does the following:
- Enable caching for devbox cli
- Enable caching for nix store
- Avoid github api rate limit on getting latest release
- Bump devbox cli version to 0.2.2 in CICD
> Cache devbox cli, avoid github api rate limit

- .github/workflows/test.yaml
- README.md
- action.yml
The install action now supports a sha256 checksum of the resulting binary. In the event that jetpack's devbox install script is compromised, this will allow users to double check that the resulting binary has a checksum configured at the github action level, potentially preventing a breach of CI infrastructure.
> Add SHA256 checksum to install action.

- .github/workflows/test.yaml
- action.yml
- testdata/devbox.json
- Update test version to 0.5.5
- Update macos test to use cache for speed
- Add new nix installation location for caching, where this logic was introduced in https://github.com/NixOS/nix/pull/5588/files and it uses XDG directory
> Update installer action to match the latest cli behavior

- .github/workflows/test.yaml
- README.md
- action.yml
Based on the suggestion at https://github.com/jetpack-io/devbox/pull/728/files#diff-e6fe83bc13b20d4fd513659c4b2cb8c34617a4b1f04e95b390517c42e905867fR134.
I have used this as a step in my own workflows and it works but would be great if it could be included in this action.
> feat: Configure nix access token to prevent GitHub rate limiting

- .github/workflows/test.yaml
- README.md
- action.yml
- testdata/devbox.lock
macOS caching is broken. This PR fixes it. This is related to `gtar` not having `sudo` permission, but `/nix/store` requires sudo. There are many many related issues out there. eg. https://github.com/actions/cache/issues/749
I also switched to using DeterminateSystems nix installer. However, I noticed that even though cache is successfully restored in the latest round of CICD, we are still fetching the binaries from remote? (at least based on the log lines) Why is that?
I suspect that I'm missing some sqlite data in the cached files. cc @savil @gcurtis if any of you have insights into this.
EDIT: SOLVED. Added xdg paths in the cache and it reduces the time by half. 🎉 🎉 🎉 
closes https://github.com/jetpack-io/devbox-install-action/issues/13
> Fix macos caching issue

- action.yml
Reverts jetpack-io/devbox-install-action#20
This results in the `~/.cache` directory gets created under `root` instead of `runner`. Reverting fix this problem.
Verified the fix with https://github.com/jetpack-io/devbox-install-action/pull/21
> Revert "Narrow the cache of xdg directory"

- README.md
- action.yml
We have some problems in our custom runner with this action so I've tried it with skipping the installation via the included action and it works in our runners (we do not use the GitHub provided ones, we are using custom runners).
In case you are wondering which action we are using, we use: `cachix/install-nix-action@v23` - I guess it has something to do with the usage of `sudo` in the other action but I'm not 100% sure on that.
I'm also not sure about the differences between these two actions so I've opted for the possibility to skip the installation rather than changing the action as I guess you've put a lot of thought into which action to use.
Edit: I need to correct myself, it's not because of `sudo` but because of `systemd`. I tried to run the action without `systemd` by passing in …
> feat: skip-nix-install

- action.yml
Instead of letting `action/cache` do the restoring and saving cache for us, we choose when to restore and when to save cache.
In this case, we will be saving cache immediately after the devbox package installation, instead of waiting for the action post run. This way, the `tar` sudo permission stays intact until the cache is saved.
More specifically, `action/cache/save` runs before the last step of restoring `tar` to its original permission (as oppose to after)
> Replace github cache action with restore and save

- action.yml
TSIA. Addressing the following warning:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache/restore@v3, [...] For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> Upgrade action cache version

- action.yml
GitHub recommends pinning 3rd party actions for security and reproducibility.  This should be a familiar idea for folks who've worked with Nix. 😄
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
For now, I've excluded dependencies from `actions/` as these are "2nd party" actions, developed and published by GitHub.  We have higher trust that GitHub published actions won't spuriously force push tag values, resulting in non deterministic runtime behavior.
If you'd like to pin all dependencies, let me know and I'll update this to include everything.  This will result in a higher sustaining burden, as Dependabot (https://github.com/jetpack-io/devbox-install-action/pull/31) will generate many more updates for pinned `actions/` …
> Pin DeterminateSystems/nix-installer-action to SHA

- .github/dependabot.yml
This will help ensure that upstream GitHub actions stay up to date.  It operationalizes updates like https://github.com/jetpack-io/devbox-install-action/pull/30 such that they're never missed.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
You can see the PRs that this config will open in my fork here:
https://github.com/wadells/devbox-install-action/pulls?q=+is%3Apr+author%3Aapp%2Fdependabot+
> Add Dependabot config for GitHub Actions

- action.yml
Use architecture as part of the cache key to avoid bad cache hits. The current implementation can crash pipelines using matrix strategies or when different pipelines use different architectures but leverage the Devbox action.
Fixes: #35
> fix: use architecture as part of cache key

- .gitignore
- action.yml
Running into intermitent failures installing nix in [devbox](https://github.com/jetify-com/devbox) here see https://github.com/jetify-com/devbox/actions/runs/8808402110/job/24177427710?pr=2017
Bumping detsys installer to see if it helps.
> [detsys] Bump detsys installer

- .github/workflows/test.yaml
- action.yml
Fixes compatibility with macos-14.
macos-14 changed the location of `gtar`, this PR fixes that.
> [macos] Fix latest macos

- action.yml
Addresses https://github.com/jetify-com/devbox-install-action/issues/49
The `runner` user on self hosted runners does not have access to `/usr/local/bin` path. This result in cache restore failures at `/usr/local/bin`. 
We can install devbox at user's home directory and make it accessible to subsequent actions.
> fix: use devbox from ~/.local/bin

- action.yml
Update action.yml devbox CLI cache location.
Addresses https://github.com/jetify-com/devbox-install-action/issues/49
> Update action.yml devbox CLI cache location

- .github/workflows/test.yaml
- README.md
- action.yml
Sometimes nix ship backwards incompatible changes, which may result in devbox installation error. The following remedy is considered:
Addresses https://github.com/jetify-com/devbox-install-action/issues/64
> Add nix version as part of the nix cache key

- action.yml
Consolidate devbox cli path. This unintended change was introduced by #65. This is a revert on the CLI path.
> Consolidate devbox cli path

- .github/workflows/test.yaml
- README.md
- action.yml
Fixes: #74 
When running actions on self-hosted GitHub Enterprise (GHES) installations, the `github.token` provided is specific to the private GHES instance. This token cannot be used to access resources on `github.com`. While the existing configuration option `disable-nix-access-token` allows users to disable the usage of `github.token` as a Nix access token, this workaround fails once the unauthenticated rate limit for `api.github.com` is exceeded.
Currently, there is no mechanism to configure a custom, working Nix access token for such scenarios. This limitation creates challenges for GHES users who need to:
- Authenticate against `api.github.com` without exceeding rate limits.
- Configure Nix access tokens for other APIs, such as private hosts, when using Nix packages from private …
> feat(action): Add extra-nix-config input for custom nix.conf settings
